version: '3'

services:
  app:
    build: ./docker
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - ./server:/app
    tty: true
    stdin_open: true
    command: /bin/sh
